Added new textures to multiblocks
SymmetricDevs/Susy-Core pull request #126
Opened 2023-08-20 20:53 UTC by Supernoobv

# What
Added new Textures to some multiblocks

# Implementation Details
This changes the current textuers for most of the multiblocks from the default in gtceu to unique ones.

2023-08-20 20:58 UTC, planetme requested changes
I think the arc furnace one is kinda weird, when it is active, the entire rod inside should glow.

2023-08-20 20:58 UTC, planetme commented on src/main/java/supersymmetry/client/renderer/textures/SusyTextures.java
> +    // not typing allat
remove

2023-08-20 23:04 UTC, Supernoobv commented on src/main/java/supersymmetry/client/renderer/textures/SusyTextures.java
> +    // not typing allat
Done

2023-08-21 14:29 UTC, loxoDev approved these changes

2023-08-21 20:44 UTC, planetme commented on src/main/java/supersymmetry/client/renderer/textures/SusyTextures.java
> +    // not typing allat
oh I meant as in remove the comment

2023-08-23 02:11 UTC, planetme commented
oh I meant as in remove the comment, not the 3 overlays

you can safely revert 42c5dc2

2023-08-26 13:11 UTC, planetme approved these changes
loooks good to me, but we might want to add some more detailing to the following overlays later:
- arc furnace
- rotary kiln

2023-09-04 03:05 UTC, merged